# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16f46e7833bc8487023c44144728ecb3d9de378782c632d5b74d46fa599d0be4efe3773e9579c097b843a863335d4995dbf9b68d02b5798a502d6f286520e34e

test:
  secret_key_base: a51be693158498e650fab56c9eda82f21f0db826779e92a6b733f1944ef124db201a8556a482bfe075f8c5fe50b79ecf9b3fca44ac50987095a583fafe970a10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
